/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.jogo.da.velha;

import java.awt.Color;
import java.util.Scanner;

/**
 *
 * @author evertonlourens
 */
public class Jogo extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Jogo.class.getName());

    /**
     * Creates new form Jogo
     */
    public Jogo() {
        initComponents();
        labelTitulo.setText("JOGO DA VELHA");
    }

    public void reiniciarJogo() {
        this.dispose();            // Fecha a janela atual
        new Jogo().setVisible(true);  // Abre uma nova igual
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        panelDois = new javax.swing.JPanel();
        labelDois = new javax.swing.JLabel();
        panelTres = new javax.swing.JPanel();
        labelTres = new javax.swing.JLabel();
        panelQuatro = new javax.swing.JPanel();
        labelQuatro = new javax.swing.JLabel();
        panelCinco = new javax.swing.JPanel();
        labelCinco = new javax.swing.JLabel();
        panelSeis = new javax.swing.JPanel();
        labelSeis = new javax.swing.JLabel();
        panelSete = new javax.swing.JPanel();
        labelSete = new javax.swing.JLabel();
        panelOito = new javax.swing.JPanel();
        labelOito = new javax.swing.JLabel();
        panelNove = new javax.swing.JPanel();
        labelNove = new javax.swing.JLabel();
        panelUm = new javax.swing.JPanel();
        labelUm = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        panelDois.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelDoisMouseClicked(evt);
            }
        });

        labelDois.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelDois.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDois.setText("2");
        labelDois.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelDoisMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelDoisLayout = new javax.swing.GroupLayout(panelDois);
        panelDois.setLayout(panelDoisLayout);
        panelDoisLayout.setHorizontalGroup(
            panelDoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelDois, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        panelDoisLayout.setVerticalGroup(
            panelDoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelDois, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelTres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelTresMouseClicked(evt);
            }
        });

        labelTres.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelTres.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTres.setText("3");
        labelTres.setPreferredSize(new java.awt.Dimension(21, 48));
        labelTres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelTresMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelTresLayout = new javax.swing.GroupLayout(panelTres);
        panelTres.setLayout(panelTresLayout);
        panelTresLayout.setHorizontalGroup(
            panelTresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelTresLayout.setVerticalGroup(
            panelTresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTres, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        panelQuatro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelQuatroMouseClicked(evt);
            }
        });

        labelQuatro.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelQuatro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelQuatro.setText("4");
        labelQuatro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelQuatroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelQuatroLayout = new javax.swing.GroupLayout(panelQuatro);
        panelQuatro.setLayout(panelQuatroLayout);
        panelQuatroLayout.setHorizontalGroup(
            panelQuatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelQuatro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelQuatroLayout.setVerticalGroup(
            panelQuatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelQuatro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelCinco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelCincoMouseClicked(evt);
            }
        });

        labelCinco.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelCinco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCinco.setText("5");
        labelCinco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelCincoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelCincoLayout = new javax.swing.GroupLayout(panelCinco);
        panelCinco.setLayout(panelCincoLayout);
        panelCincoLayout.setHorizontalGroup(
            panelCincoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelCinco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelCincoLayout.setVerticalGroup(
            panelCincoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelCinco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelSeis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelSeisMouseClicked(evt);
            }
        });

        labelSeis.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelSeis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSeis.setText("6");
        labelSeis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelSeisMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelSeisLayout = new javax.swing.GroupLayout(panelSeis);
        panelSeis.setLayout(panelSeisLayout);
        panelSeisLayout.setHorizontalGroup(
            panelSeisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelSeis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelSeisLayout.setVerticalGroup(
            panelSeisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelSeis, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        panelSete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelSeteMouseClicked(evt);
            }
        });

        labelSete.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelSete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSete.setText("7");
        labelSete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelSeteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelSeteLayout = new javax.swing.GroupLayout(panelSete);
        panelSete.setLayout(panelSeteLayout);
        panelSeteLayout.setHorizontalGroup(
            panelSeteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelSete, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        panelSeteLayout.setVerticalGroup(
            panelSeteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelSete, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        panelOito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelOitoMouseClicked(evt);
            }
        });

        labelOito.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelOito.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelOito.setText("8");
        labelOito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelOitoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelOitoLayout = new javax.swing.GroupLayout(panelOito);
        panelOito.setLayout(panelOitoLayout);
        panelOitoLayout.setHorizontalGroup(
            panelOitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelOito, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        panelOitoLayout.setVerticalGroup(
            panelOitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelOito, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        panelNove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelNoveMouseClicked(evt);
            }
        });

        labelNove.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelNove.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNove.setText("9");
        labelNove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelNoveMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelNoveLayout = new javax.swing.GroupLayout(panelNove);
        panelNove.setLayout(panelNoveLayout);
        panelNoveLayout.setHorizontalGroup(
            panelNoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelNove, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        panelNoveLayout.setVerticalGroup(
            panelNoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelNove, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        panelUm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelUmMouseClicked(evt);
            }
        });

        labelUm.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelUm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelUm.setText("1");
        labelUm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelUmMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelUmLayout = new javax.swing.GroupLayout(panelUm);
        panelUm.setLayout(panelUmLayout);
        panelUmLayout.setHorizontalGroup(
            panelUmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelUm, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        panelUmLayout.setVerticalGroup(
            panelUmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelUm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        labelTitulo.setText("JOGO DA VELHA");

        jLabel1.setText("jLabel1");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("By: Everton Lourens");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Reiniciar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(panelSete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelOito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelNove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(panelUm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelQuatro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelDois, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelCinco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelSeis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelTres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(labelTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTitulo)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelUm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelDois, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelQuatro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCinco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelSeis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelOito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelNove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelSete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void panelUmMouseClicked(java.awt.event.MouseEvent evt) {                                     
        if (jogoEncerrado == false) {
            if (numJogador == -1) {
                labelUm.setText("X");
            } else if (numJogador == -2) {
                labelUm.setText("O");
            }
            iniciarJogo(1);
        }
    }                                    

    private void labelUmMouseClicked(java.awt.event.MouseEvent evt) {                                     
        if (jogoEncerrado == false) {
            if (numJogador == -1) {
                labelUm.setText("X");
            } else if (numJogador == -2) {
                labelUm.setText("O");
            }
            iniciarJogo(1);
        }
    }                                    

    private void panelDoisMouseClicked(java.awt.event.MouseEvent evt) {                                       
        if (jogoEncerrado == false) {
            if (numJogador == -1) {
                labelDois.setText("X");
            } else if (numJogador == -2) {
                labelDois.setText("O");
            }
            iniciarJogo(2);
        }
    }                                      

    private void labelDoisMouseClicked(java.awt.event.MouseEvent evt) {                                       
        if (jogoEncerrado == false) {
            if (numJogador == -1) {
                labelDois.setText("X");
            } else if (numJogador == -2) {
                labelDois.setText("O");
            }
            iniciarJogo(2);
        }
    }                                      

    private void labelTresMouseClicked(java.awt.event.MouseEvent evt) {                                       
        if (jogoEncerrado == false) {
            if (numJogador == -1) {
                labelTres.setText("X");
            } else if (numJogador == -2) {
                labelTres.setText("O");
            }
            iniciarJogo(3);
        }
    }                                      

    private void panelTresMouseClicked(java.awt.event.MouseEvent evt) {                                       
        if (jogoEncerrado == false) {
            if (numJogador == -1) {
                labelTres.setText("X");
            } else if (numJogador == -2) {
                labelTres.setText("O");
            }
            iniciarJogo(3);
        }
    }                                      

    private void panelQuatroMouseClicked(java.awt.event.MouseEvent evt) {                                         
        if (jogoEncerrado == false) {
            if (numJogador == -1) {
                labelQuatro.setText("X");
            } else if (numJogador == -2) {
                labelQuatro.setText("O");
            }
            iniciarJogo(4);
        }
    }                                        

    private void labelQuatroMouseClicked(java.awt.event.MouseEvent evt) {                                         
        if (jogoEncerrado == false) {
            if (numJogador == -1) {
                labelQuatro.setText("X");
            } else if (numJogador == -2) {
                labelQuatro.setText("O");
            }
            iniciarJogo(4);
        }
    }                                        

    private void labelCincoMouseClicked(java.awt.event.MouseEvent evt) {                                        
        if (jogoEncerrado == false) {
            if (numJogador == -1) {
                labelCinco.setText("X");
            } else if (numJogador == -2) {
                labelCinco.setText("O");
            }
            iniciarJogo(5);
        }
    }                                       

    private void panelCincoMouseClicked(java.awt.event.MouseEvent evt) {                                        
        if (jogoEncerrado == false) {
            if (numJogador == -1) {
                labelCinco.setText("X");
            } else if (numJogador == -2) {
                labelCinco.setText("O");
            }
            iniciarJogo(5);
        }
    }                                       

    private void labelSeisMouseClicked(java.awt.event.MouseEvent evt) {                                       
        if (jogoEncerrado == false) {
            if (numJogador == -1) {
                labelSeis.setText("X");
            } else if (numJogador == -2) {
                labelSeis.setText("O");
            }
            iniciarJogo(6);
        }
    }                                      

    private void panelSeisMouseClicked(java.awt.event.MouseEvent evt) {                                       
        if (jogoEncerrado == false) {
            if (numJogador == -1) {
                labelSeis.setText("X");
            } else if (numJogador == -2) {
                labelSeis.setText("O");
            }
            iniciarJogo(6);
        }
    }                                      

    private void panelSeteMouseClicked(java.awt.event.MouseEvent evt) {                                       
        if (jogoEncerrado == false) {
            if (numJogador == -1) {
                labelSete.setText("X");
            } else if (numJogador == -2) {
                labelSete.setText("O");
            }
            iniciarJogo(7);
        }
    }                                      

    private void labelSeteMouseClicked(java.awt.event.MouseEvent evt) {                                       
        if (jogoEncerrado == false) {
            if (numJogador == -1) {
                labelSete.setText("X");
            } else if (numJogador == -2) {
                labelSete.setText("O");
            }
            iniciarJogo(7);
        }
    }                                      

    private void labelOitoMouseClicked(java.awt.event.MouseEvent evt) {                                       
        if (jogoEncerrado == false) {
            if (numJogador == -1) {
                labelOito.setText("X");
            } else if (numJogador == -2) {
                labelOito.setText("O");
            }
            iniciarJogo(8);
        }
    }                                      

    private void panelOitoMouseClicked(java.awt.event.MouseEvent evt) {                                       
        if (jogoEncerrado == false) {
            if (numJogador == -1) {
                labelOito.setText("X");
            } else if (numJogador == -2) {
                labelOito.setText("O");
            }
            iniciarJogo(8);
        }
    }                                      

    private void labelNoveMouseClicked(java.awt.event.MouseEvent evt) {                                       
        if (jogoEncerrado == false) {
            if (numJogador == -1) {
                labelNove.setText("X");
            } else if (numJogador == -2) {
                labelNove.setText("O");
            }
            iniciarJogo(9);
        }
    }                                      

    private void panelNoveMouseClicked(java.awt.event.MouseEvent evt) {                                       
        if (jogoEncerrado == false) {
            if (numJogador == -1) {
                labelNove.setText("X");
            } else if (numJogador == -2) {
                labelNove.setText("O");
            }
            iniciarJogo(9);
        }
    }                                      

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       reiniciarJogo();
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Jogo().setVisible(true));
    }

    public void iniciarJogo(int inputJogador) {
        for (int x = 0; x < matJogo.length; x++) {
            for (int y = 0; y < matJogo[0].length; y++) {
                // Se o input do jogador for igual ao número da matriz, coloca -1 para o jogador
                // 1 ou -2 para marcar
                // a posição escolhida
                if (inputJogador == matJogo[x][y]) { // Jogador 1 faz sua jogada:
                    if (numJogador == -1) {
                        // A escolha do primeiro jogador é marcada com '-1' na matriz
                        matJogo[x][y] = -1;
                        // Confere se o jogo foi vencido pelo jogador atual
                        jogoEncerrado = conferirJogo(matJogo, numJogador);
                        if (jogoEncerrado == false) {
                            // passa a vez para o próximo jogador se o jogo não foi encerrado
                            numJogador = -2;
                        }
                    } else if (numJogador == -2) { // Jogador 2 faz sua jogada:
                        // A escolha do primeiro jogador é marcada com '-2' na matriz
                        matJogo[x][y] = -2;
                        // Confere se o jogo foi vencido pelo jogador atual
                        jogoEncerrado = conferirJogo(matJogo, numJogador);
                        if (jogoEncerrado == false) {
                            // passa a vez para o próximo jogador se o jogo não foi encerrado
                            numJogador = -1;
                        }
                    }
                } else {
                    // Não permite o jogo encerrar caso o jogador escolha um número inválido ou uma
                    // letra
                    i--;
                    j--;
                }
            }
        }
        // Mostrando a matriz com a escolha do último jogador
        mostrarJogo(matJogo);

        if (jogoEncerrado == false) {
            // Confere se ainda há opções para jogar ou se deu velha
            deuVelha = checkOpcoes(matJogo);
            jogoEncerrado = deuVelha;
        }

        // Conferindo se o jogo já foi encerrado (deu velha ou não resta opções para
        // jogar)
        if (jogoEncerrado == true) {
            System.out.println("Jogo encerrado! Não há mais jogadas possíveis.");
            if (deuVelha == true) {
                System.out.println("===>>> DEU VELHA! <<<===");
            } else {
                System.out.println("===>>> JOGADOR " + (numJogador * -1) + " VENCEU! <<<===");
                labelTitulo.setText("Jogador " + (numJogador * -1) + " venceu!");
                labelTitulo.setForeground(Color.green);
                jPanel1.setEnabled(false);
                jPanel2.setEnabled(false);

                labelCinco.setEnabled(false);
                labelDois.setEnabled(false);
                labelNove.setEnabled(false);
                labelOito.setEnabled(false);
                labelQuatro.setEnabled(false);
                labelSeis.setEnabled(false);
                labelSete.setEnabled(false);
                labelTres.setEnabled(false);
                labelUm.setEnabled(false);

                panelCinco.setEnabled(false);
                panelDois.setEnabled(false);
                panelNove.setEnabled(false);
                panelOito.setEnabled(false);
                panelQuatro.setEnabled(false);
                panelSeis.setEnabled(false);
                panelSete.setEnabled(false);
                panelTres.setEnabled(false);
                panelUm.setEnabled(false);
            }
        }
    }

    public static boolean conferirJogo(int matJogo[][], int numJogador) {
        boolean jogoEncerrado = false;
        if (jogoEncerrado == false) {
            jogoEncerrado = checkDiagEsquerDirei(matJogo, numJogador);
        }
        if (jogoEncerrado == false) {
            jogoEncerrado = checkDiagDireiEsquer(matJogo, numJogador);
        }
        if (jogoEncerrado == false) {
            jogoEncerrado = checkHorizEsquerDirei(matJogo, numJogador);
        }
        if (jogoEncerrado == false) {
            jogoEncerrado = checkVertEsquerDirei(matJogo, numJogador);
        }
        return jogoEncerrado;
    }

    public static boolean checkOpcoes(int mat[][]) {
        // Inicia a variável como verdadeira para conferir se há números restantes na
        // matriz
        boolean jogoEncerrado = true;
        for (int i = 0; i < mat.length; i++) {
            for (int j = 0; j < mat[0].length; j++) {
                if (mat[i][j] > 0) {
                    // Se houver algum número positivo, significa que ainda existe opções para jogar
                    // e o jogo não pode ser encerrado
                    jogoEncerrado = false;
                    break;
                }
            }
        }
        return jogoEncerrado;
    }

    public static void mostrarJogo(int mat[][]) {
        System.out.println("=========");
        // Mostrando a matriz padrão para os jogadores escolherem os números
        for (int i = 0; i < mat.length; i++) {
            System.out.print("|");
            for (int j = 0; j < mat[0].length; j++) {
                if (mat[i][j] == -1) {
                    // Se a matriz tiver algum número '0', marca 'X' para indicar o jogador 1
                    if (mat[0].length == j + 1) {
                        System.out.print("X" + "|");
                    } else {
                        System.out.print("X" + "  ");
                    }
                } else if (mat[i][j] == -2) {
                    // Se a matriz tiver algum número '-1', marca 'O' para indicar o jogador 2

                    if (mat[0].length == j + 1) {
                        System.out.print("O" + "|");
                    } else {
                        System.out.print("O" + "  ");
                    }
                } else {
                    // Senão, mostra apenas os números restantes na matriz para os jogadores
                    // escolherem
                    if (mat[0].length == j + 1) {
                        System.out.print(mat[i][j] + "|");
                    } else {
                        System.out.print(mat[i][j] + "  ");
                    }
                }

            }
            System.out.println(" ");
        } // Encerra a exibição
        System.out.println("=========");
    }

    public static boolean checkDiagEsquerDirei(int mat[][], int num) {
        boolean identidade = true;
        // Confere se é identidade pela diagonal da esquerda para a direita, de cima
        // para baixo
        for (int i = 0; i < mat.length; i++) {
            for (int j = 0; j < mat[0].length; j++) {

                if ((i == j) && (mat[i][j] != num)) {
                    identidade = false;
                }

                /*
                 * Independente se for identidade ou não, se tiver 1's da diagonal, deve
                 * retornar true para mostrar que venceu o jogo
                 * if ((i != j) && (mat[i][j] != 0)) {
                 * identidade = false;
                 * }
                 */
            }
        }
        return identidade;
    }

    public static boolean checkDiagDireiEsquer(int mat[][], int num) {
        boolean identidade = true;
        // Confere se é identidade pela diagonal da direita para a esquerda, de cima
        // para baixo
        for (int i = 0; i < mat.length; i++) {
            for (int j = mat[0].length - 1; j >= 0; j--) {

                if ((mat[i][(mat[0].length - i) - 1] != num)) {
                    identidade = false;
                }

                /*
                 * Independente se for identidade ou não, se tiver 1's da diagonal, deve
                 * retornar true para mostrar que venceu o jogo
                 * if ((mat[i][j] != 0) && (j != (mat[0].length - i) - 1)) {
                 * identidade = false;
                 * }
                 */
            }
        }
        return identidade;
    }

    public static boolean checkHorizEsquerDirei(int mat[][], int num) {
        int count = 0;
        // Confere se é identidade pela horizontal da esquerda para a direita, de cima
        // para baixo
        for (int i = 0; i < mat.length; i++) {
            if (count == mat[0].length) {
                break;
            } else {
                count = 0;
            }
            for (int j = 0; j < mat[0].length; j++) {
                if (mat[i][j] == num) {
                    count++;
                } else {
                    break;
                }
            }
        }
        return count == mat[0].length;
    }

    public static boolean checkVertEsquerDirei(int mat[][], int num) {
        int count = 0;
        // Confere se é identidade pela vertical da esquerda para a direita, de cima
        // para baixo
        for (int i = 0; i < mat.length; i++) {
            if (count == mat.length) {
                break;
            } else {
                count = 0;
            }
            for (int j = 0; j < mat[0].length; j++) {
                if (mat[j][i] == num) {
                    count++;
                } else {
                    break;
                }
            }
        }
        return count == mat.length;
    }

    public void mudarLabel() {
        labelUm.setText("A");
        labelDois.setText("B");
    }

    // Inicializando matriz padrão do jogo para o jogador escolher os números
    public int matJogo[][] = {
        {1, 2, 3},
        {4, 5, 6},
        {7, 8, 9},};
    public int i, j;
    public int numJogador = -1;
    public boolean jogoEncerrado = false;
    public boolean deuVelha = false;
    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelCinco;
    private javax.swing.JLabel labelDois;
    private javax.swing.JLabel labelNove;
    private javax.swing.JLabel labelOito;
    private javax.swing.JLabel labelQuatro;
    private javax.swing.JLabel labelSeis;
    private javax.swing.JLabel labelSete;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelTres;
    public javax.swing.JLabel labelUm;
    private javax.swing.JPanel panelCinco;
    private javax.swing.JPanel panelDois;
    private javax.swing.JPanel panelNove;
    private javax.swing.JPanel panelOito;
    private javax.swing.JPanel panelQuatro;
    private javax.swing.JPanel panelSeis;
    private javax.swing.JPanel panelSete;
    private javax.swing.JPanel panelTres;
    private javax.swing.JPanel panelUm;
    // End of variables declaration                   
}
